version: "3.8"
services:
  postgres-logistics:
    image: postgres:15.1-alpine
    container_name: postgres-logistics
    restart: unless-stopped
    environment:
      POSTGRES_USER: logistics
      POSTGRES_PASSWORD: logistics
      POSTGRES_DB: logistics
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - logistics_network
  
  logistics-app:
    image: cosmtrek/air
    working_dir: /logistics
    ports:
      - 8181:8181
    volumes:
      - ./logistics:/logistics
    networks:
      - logistics_network

volumes:
  db:
    driver: local

networks:
  logistics_network:
    driver: bridge